name: pytest-pyspark-utils CI

on:
  pull_request:
    paths:
      - "pytest_pyspark_utils/**"
      - "tests/**"
      - ".github/workflows/ci.yaml"
      - ".pre-commit-config.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: "CI: pytest-pyspark-utils"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --group dev

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Run tests with coverage
        run: uv run pytest --cache-clear --cov=pytest_pyspark_utils tests/ > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
